config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "lists#index"
  resources :lists, only: [:new, :show, :create] do
    resources :bookmarks, only: [:new, :create]
  end

  resources :bookmarks, only: :destroy

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates :comment, length: { minimum: 6 }
  validates :movie_id, uniqueness: { scope: :list_id,
  message: "Already in the list" }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  validates :title, :overview, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
   before_action :set_list, only: [:new, :create]
  def new
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    @bookmark.save!
    redirect_to list_path(@list)
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @list = @bookmark.list
    @bookmark.destroy
    redirect_to list_path(@list), status: :see_other
  end

  private

  def set_list
    @list = List.find(params[:list_id])
  end

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def new
    @list = List.new
  end

  def show
    @list = List.find(params[:id])
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def list_params
    params.require(:list).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/new.html.erb
<h1>New Bookmark</h1>
<%= simple_form_for [@list, @bookmark] do |f| %>
  <%= f.input :comment %>
  <%= f.association :movie %>
  <%= f.submit "Submit Bookmark", class: "btn btn-primary" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<div class="container">
<h1>Here are my lists</h1>
<br>
  <ul>
    <% @lists.each do |list| %>
      <li><%= link_to list.name, list_path(list) %></li>
    <% end %>
  </ul>
  <%= link_to 'New List', new_list_path%>
</div>

app/views/lists/new.html.erb
<h1>New List</h1>
<%= simple_form_for @list do |f| %>
  <%= f.input :name %>
  <%= f.submit "Submit list", class: "btn btn-primary" %>
<% end %>

app/views/lists/show.html.erb
<div class="container">
    <p><strong>List</strong></p>
    <%= @list.name %>
    <br>
    <%= link_to "Back to all lists", root_path %>
    <%= link_to "New bookmark", new_list_bookmark_path(@list) %>

  <div class="row">
    <p><strong>Bookmarks</strong></p>
      <% @list.bookmarks.each do |bookmark| %>
      <div class="card col mx-4">
        <img src="<%=bookmark.movie.poster_url%>" alt="Movie poster">
        <h3><%= bookmark.movie.title %></h3>
        <p><%= bookmark.movie.overview %></p>
        <div class="bottom-card">
           <p class="list-group-item"><i class="fa-solid fa-quote-left"></i> <%= bookmark.comment %></p>
          <%= link_to bookmark_path(bookmark), data: {turbo_method: :delete, turbo_confirm: 'Are you sure?'} do %>
            <p class="btn-delete">Delete </p>
          <% end %>
        </div>
      </div>
      <% end %>
  </div>
</div>